Repository mainmatter/ember-vite-codemod, pull requests merged in 2025-03, with the labels that each got.

#26 Add ember-composable-helpers and ember-cli-mirage to unsupported deps
  lib/tasks/ensure-no-unsupported-deps.js
Labels: enhancement

#27 Support apps building with @embroider/webpack
  README.md
  index.js
  lib/tasks/transform-files.js
  lib/transforms/ember-cli-build.js
  package.json
  pnpm-lock.yaml
  tests/all-versions.test.js
  tests/test-helpers.js
Labels: enhancement

#33 Remove devDep portfinder
  package.json
  pnpm-lock.yaml
  vitest.config.js
Labels: internal

#35 move recast to a dependency
  package.json
  pnpm-lock.yaml
Labels: bug

#39 make sure the codemod doesn't exit if it comes across private packages
  index.js
  lib/tasks/ensure-v2-addons.js
  lib/tasks/ensure-v2-addons.test.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#47 Add `ember-template-imports` to packagesToRemove
  lib/tasks/update-package-json.js
Labels: enhancement

#49 split out webpack and typescript tests properly
  .github/workflows/ci.yml
  tests/all-versions.test.js
  tests/standard.test.js
  tests/test-helpers.js
  tests/typescript.test.js
  tests/webpack.test.js
Labels: internal

#51 add fail-fast: false to CI matrix
  .github/workflows/ci.yml
Labels: internal

#15 bump minimum embroider versions and enable testing for ember-5.8
  lib/tasks/update-package-json.js
  tests/test-helpers.js
Labels: enhancement

#24 enable tests for Ember 5.4
  lib/tasks/update-package-json.js
  tests/test-helpers.js
  vitest.config.js
Labels: enhancement

#57 add a --environment=production test
  tests/fixtures/app/components/welcome-page.js
  tests/test-helpers.js
Labels: internal

#59 split CI by ember version
  .github/workflows/ci.yml
Labels: internal

#53 enable testing for ember 4.12
  .github/workflows/ci.yml
  lib/tasks/update-package-json.js
  tests/test-helpers.js
Labels: enhancement

#54 enable testing for 4.8
  .github/workflows/ci.yml
  tests/test-helpers.js
Labels: enhancement

#63 Remove `@embroider/webpack` + don't report `@embroider/macros` and `@embroider/util`
  lib/tasks/ensure-v2-addons.js
  lib/tasks/update-package-json.js
Labels: enhancement

#52 Throw error when modulePrefix does not match package.json#name
  index.js
  lib/tasks/check-modulePrefix-mismatch.js
Labels: bug

#56 enable testing for 4.4
  .github/workflows/ci.yml
  tests/test-helpers.js
Labels: enhancement

#60 Enable ember 3.28
  .github/workflows/ci.yml
  tests/fixtures/tests/helpers/index.js
  tests/test-helpers.js
Labels: enhancement

#68 bump minimum version of @embroider/compat
  lib/tasks/update-package-json.js
Labels: enhancement

#74 Fix/ in ensure-v2-addons, look for local package.json first
  lib/tasks/ensure-v2-addons.js
  lib/tasks/ensure-v2-addons.test.js
Labels: enhancement
