Repository mainmatter/ember-vite-codemod, pull requests merged in 2025-02, with the labels that each got.

#12 set up release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#11 add a basic CI
  .github/workflows/ci.yml
  .npmrc
  lib/tasks/add-missing-files.js
  lib/tasks/update-package-json.js
  lib/transforms/index-html.js
  package.json
  pnpm-lock.yaml
  tests/all-versions.test.js
  vitest.config.js
Labels: internal

#16 Check if the repository is clean
  index.js
  lib/tasks/check-git-status.js
  tests/all-versions.test.js
Labels: enhancement

#14 Add a README.md
  README.md
Labels: documentation

#18 Iterate on ensure-v2-addon task
  README.md
  lib/tasks/ensure-v2-addons.js
Labels: enhancement

#17 Add `/tmp/` at to the top of .gitignore if not found
  lib/tasks/transform-files.js
Labels: enhancement

#22 ignore changelog for linting
  .prettierignore
Labels: internal

#21 Support Ember 5.12 (by updating packages)
  lib/tasks/ensure-v2-addons.js
  lib/tasks/update-package-json.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#19 Enable testing for Ember 5.12
  tests/all-versions.test.js
  tests/fixtures/index-test.js
Labels: internal
